const request = require('supertest')
const app = require('../app.js')
const testData = require('../db/data/test-data/index')
const seed = require('../db/seeds/seed.js')
// const db = require('../db')
// beforeEach(() => seed(testData))
// afterAll(() => db.end())